<?php
if(!isset($_SESSION['mail']))
{
session_start();
}
if(!isset($_GET['groupe']))
{
	include_once'../controleur/Accueil.php';
}else{
include_once'../modele/get_groupes.php';
$groupes=get_groupes($_GET['groupe'],'');
include_once'../vue/Groupe.php';
}
?>